plugins {
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
}

android {
    namespace "com.example.bama"
    compileSdk 37

    defaultConfig {
        applicationId "com.example.bama"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
}

kotlin {
    jvmToolchain(17)
}
